version: '3.8'
services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - VERCEL_FRONTEND_URL=${VERCEL_FRONTEND_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  coturn:
    build:
      context: ./coturn
    network_mode: host
    volumes:
      - ./coturn/certs:/certs
    environment:
      - EXTERNAL_IP=157.230.57.181
    restart: unless-stopped
volumes:
  redis-data:
